services:
  hono-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    environment:
      - TARGET_ENVIRONMENT=${TARGET_ENVIRONMENT}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - astro_build:/app/public
    depends_on:
      frontend:
        condition: service_started
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore: node_modules/
        - action: rebuild
          path: ./server/deno.json
  frontend:
    build:
      context: ./client/
      dockerfile: Dockerfile
    restart: on-failure:5
    environment:
      - TARGET_ENVIRONMENT=${TARGET_ENVIRONMENT}
    volumes:
      - astro_build:/app/dist
    develop:
      watch:
        - action: sync
          path: ./client/
          target: /app/
          ignore: node_modules/
        - action: rebuild
          path: ./client/package.json
  caddy:
    image: caddy:2.10.0-alpine
    restart: unless-stopped
    # Caddy ships with HTTP/3 support enabled by default. To improve the
    # performance of this UDP based protocol, the underlying quic-go library
    # tries to increase the buffer sizes for its socket. The NET_ADMIN
    # capability allows it to override the low default limits of the operating
    # system without having to change kernel parameters via sysctl. Giving the
    # container this capability is optional and has potential, though unlikely,
    # to have security implications.
    # See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for more
    # details.
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      # Named volumes for Caddy's persistent data (like generated certs)
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - TARGET_ENVIRONMENT=${TARGET_ENVIRONMENT}
    develop:
      watch:
        - action: sync+restart
          path: ./caddy/
          target: .
    depends_on:
      - hono-server
  db:
    image: postgres:17.5-alpine3.21
    restart: always
    shm_size: 128mb # set shared memory limit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      # $$VAR is used to ensure the variable is expanded *inside the
      # container's shell* from the container's environment, not by Docker
      # Compose from the host.
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
  adminer:
    image: adminer
    restart: always

volumes:
  caddy_data: {}
  caddy_config: {}
  astro_build: {}
  postgres_data: {}
